# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Testomatio Run

on:
  workflow_dispatch:
    inputs:
      grep:
        description: 'tests to grep '
        required: false
        default: ''
      run:
        required: false
      testomatio:
        required: false

jobs:
  build:
    name: Testomatio Run ${{ github.event.inputs.run }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Build the project
      run: npm run build --if-present
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Run Playwright tests
      run: TESTOMATIO_DEBUG=1 npx playwright test --grep "${{ github.event.inputs.grep }}"
      env:
        TESTOMATIO: "${{ github.event.inputs.testomatio }}"
        TESTOMATIO_RUN: "${{ github.event.inputs.run }}"

    - name: Upload Testomatio debug file
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: testomatio-debug
        path: /tmp/testomatio.debug.*
        retention-days: 7

    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 7